const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('assert/strict'),fs=require('fs'),path=require('path');
const d=JSON.parse(fs.readFileSync(path.join(__dirname,'../dist/agenda.json'))),out=process.env.UX_OUTPUT_DIR||path.join(__dirname,'../test-results/audit');fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch({headless:true,...(process.env.BROWSER_PATH?{executablePath:process.env.BROWSER_PATH}:{})});try{const c=await b.newContext({viewport:{width:388,height:844}}),p=await c.newPage();p.setDefaultTimeout(8000);await p.clock.install({time:new Date('2026-10-08T10:00:00Z')});const pre=d.activities.find(a=>a.date==='2026-10-07'),thu=d.activities.find(a=>a.date==='2026-10-08');await p.addInitScript(({pre,thu,version})=>localStorage.setItem('congreso-2-route-v1',JSON.stringify({schema:1,dataVersion:version,rules:{rooms:{},blocks:{},activities:{[pre]:true,[thu]:true}},signatures:{}})),{pre:pre.id,thu:thu.id,version:d.meta.version});await p.goto('http://127.0.0.1:4173');await p.waitForSelector('body[data-ready]');
for(const width of [388,485,1165]){await p.setViewportSize({width,height:844});for(const button of ['infoButton']){await p.locator('#'+button).click();const contrast=await p.locator('.dialogtop').evaluate(e=>{const rgb=x=>x.match(/[\d.]+/g).slice(0,3).map(Number),lum=x=>rgb(x).map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0),ratio=(a,b)=>{const x=lum(a),y=lum(b);return(Math.max(x,y)+.05)/(Math.min(x,y)+.05);};return [...e.children].map(x=>ratio(getComputedStyle(x).color,getComputedStyle(e).backgroundColor));});contrast.forEach(x=>assert.ok(x>4.5));assert.ok((await p.locator('#closeDetail').boundingBox()).width>=44);await p.locator('#closeDetail').click();await p.waitForFunction(()=>!document.querySelector('#detail').open);assert.equal(await p.evaluate(()=>document.activeElement.id),button);}}
await p.setViewportSize({width:388,height:844});await p.locator('#infoButton').click();await p.screenshot({animations:'disabled',path:path.join(out,'Mapa-cierre-corregido.png')});await p.keyboard.press('Escape');await p.waitForFunction(()=>!document.querySelector('#detail').open);
await p.locator('#navigation [data-tab=route]').click();assert.equal(await p.locator('#routeCount').innerText(),'2');await p.locator('[data-day="2026-10-07"]').click();assert.ok(await p.locator(`.route-entry[data-activity="${pre.id}"]`).count());assert.match(await p.locator('.route-date-label').innerText(),/1 de 2/);await p.locator('#navigation [data-tab=program]').click();assert.equal(await p.locator('[data-day="2026-10-07"]').count(),0);
await p.locator('#navigation [data-tab=now]').click();await p.locator('[data-now-mode=custom]').first().click();await p.locator('#blockDate').selectOption('2026-10-08');await p.locator('#blockTime').selectOption('11:00');await p.locator('[data-action=apply-block]').click();await p.locator('.now-chips [data-now-mode=next]').click();let text=await p.locator('#consultBanner').innerText();let time=text.match(/\d{2}:\d{2}/)[0];assert.ok(time>'11:00',text);await p.locator('.now-chips [data-now-mode=next]').click();text=await p.locator('#consultBanner').innerText();assert.ok(text.match(/\d{2}:\d{2}/)[0]>time,text);
await p.locator('[data-now-mode=custom]').first().click();await p.locator('#blockDate').selectOption('2026-10-09');await p.locator('#blockTime').selectOption('08:30');await p.locator('[data-action=apply-block]').click();await p.locator('.dense-talk [data-pick]').first().click();await p.locator('#navigation [data-tab=route]').click();assert.equal(await p.locator('[data-day="2026-10-09"]').getAttribute('aria-pressed'),'true');assert.match(await p.locator('.route-date-label').innerText(),/viernes,? 9/);await p.locator('#consultBanner [data-now-mode=now]').click();assert.equal(await p.locator('#consultBanner').isVisible(),false);
await p.locator('#navigation [data-tab=program]').click();await p.locator('[data-day="2026-10-08"]').click();const block=d.blocks.find(b=>/Hands-On/i.test(b.title));await p.locator(`[data-room="${block.roomId}"]`).click();await p.locator(`[data-group="block"][data-key="${block.id}"]`).click();assert.match(await p.locator('.group-preview').innerText(),/Almuerzo/);assert.equal(await p.locator('[data-group-rule=exclude]').isVisible(),false);await p.screenshot({animations:'disabled',path:path.join(out,'Seleccion-bloque-simplificada.png')});await p.locator('[data-group-rule=include]').click();await p.locator('#closeDetail').click();await p.waitForFunction(()=>!document.querySelector('#detail').open);await p.locator('#infoButton').click();assert.match(await p.locator('#appVersion').innerText(),/2026.10.08.22/);console.log('PASS: dialog contrast/close/focus at 388,485,1165; precongress counter reconciliation; next from consultation; Friday route alignment; group meal preview/advanced options; app version');}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});

