import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {emptyRules,setRule,selected,groupState,roomKey,overlap,conflicts,eventClock,isLive,filterActivities,loadState,validateData} from '../dist/domain.js';
// Synthetic records are test-only and never used by the production agenda.
const a={id:'test-a',date:'2026-10-08',roomId:'r',blockId:'b',title:'Prueba sintética ácida',speaker:'Persona de prueba',start:'09:00',end:'09:30',levels:[1],auxiliary:false};
const b={...a,id:'test-b',start:'09:30',end:'10:00'},c={...a,id:'test-c',roomId:'other',blockId:'other',start:'09:15',end:'09:45'};
test('individual > block > room, regardless of click order',()=>{let r=setRule(emptyRules(),'activities',a.id,false);r=setRule(r,'blocks','b',true);r=setRule(r,'rooms',roomKey(a),true);assert.equal(selected(a,r),false);assert.equal(selected(b,r),true);r=setRule(r,'activities',a.id,undefined);assert.equal(selected(a,r),true);r=setRule(r,'blocks','b',false);assert.equal(selected(a,r),false);r=setRule(r,'activities',a.id,true);assert.equal(selected(a,r),true);});
test('room selection does not select same room on another day',()=>{const r=setRule(emptyRules(),'rooms',roomKey(a),true);assert.equal(selected({...a,date:'2026-10-09'},r),false)});
test('repeating a rule is idempotent and group state derives from effective choices',()=>{const r=setRule(emptyRules(),'rooms',roomKey(a),true);assert.deepEqual(setRule(r,'rooms',roomKey(a),true),r);const except=setRule(r,'activities',a.id,false);assert.deepEqual(groupState([a,b],except),{count:1,total:2,state:'mixed'});});
test('adjacency is not overlap; same item and different dates do not conflict',()=>{assert.equal(overlap(a,b),false);assert.equal(overlap(a,a),false);assert.equal(overlap(a,{...c,date:'2026-10-09'}),false);assert.equal(overlap(a,c),true);assert.equal(overlap(a,{...c,start:null}),null);});
test('conflicts return actual pairs, preserve decisions and list missing times',()=>{let r=emptyRules();for(const x of [a,b,c])r=setRule(r,'activities',x.id,true);const before=structuredClone(r),f=conflicts([a,b,c],r);assert.equal(f.pairs.length,2);assert.ok(f.pairs.every(p=>p.minutes===15));assert.deepEqual(r,before);r=setRule(r,'activities','unknown',true);assert.equal(conflicts([a,{...b,id:'unknown',start:null}],r).unknown.length,1)});
test('clock is in Santiago, including day rollover, and boundaries are half-open',()=>{assert.deepEqual(eventClock(new Date('2026-10-08T02:30:00Z')),{date:'2026-10-07',time:'23:30'});assert.equal(isLive(a,{date:a.date,time:'09:00'}),true);assert.equal(isLive(a,{date:a.date,time:'09:30'}),false);assert.equal(isLive({...a,start:null},{date:a.date,time:'09:10'}),false)});
test('search ignores accents and filters do not mutate selections',()=>{const r=setRule(emptyRules(),'rooms',roomKey(a),true),before=structuredClone(r);assert.equal(filterActivities([a,b],{q:'acida',level:'1'},{rooms:{r:{name:'Sala prueba'}},blocks:{b:{title:'Bloque sintético'}}}).length,2);assert.deepEqual(r,before)});
test('invalid rules are rejected',()=>{assert.throws(()=>setRule(emptyRules(),'wrong','x',true));assert.throws(()=>setRule(emptyRules(),'activities','x','yes'));});
const real=JSON.parse(fs.readFileSync(new URL('../dist/agenda.json',import.meta.url),'utf8'));
test('real program is validated and has known corrections and no duplicate ceremonies',()=>{assert.deepEqual(validateData(real),[]);assert.equal(real.activities.length,387);assert.equal(real.activities.find(a=>a.id==='e59').title,'BI-RADS 3 en pacientes con cáncer de mama.');assert.equal(real.activities.find(a=>a.id==='e256').start,null);assert.equal(real.activities.find(a=>a.id==='e391').speaker,'TM María José Prokes');assert.ok(!real.activities.some(a=>['e73','e75','e381','e383'].includes(a.id)));assert.ok(real.activities.find(a=>a.id==='e8').sourceVariants.length)});
test('legacy IDs migrate to canonical ceremonies and persist',()=>{const result=loadState(null,real,JSON.stringify({e73:1,e75:1,e59:1}));assert.equal(result.state.rules.activities.e74,true);assert.equal(Object.keys(result.state.rules.activities).length,2);assert.deepEqual(loadState(JSON.stringify(result.state),real).state.rules,result.state.rules);});
test('corrupted or future-format storage is not overwritten',()=>{assert.equal(loadState('{broken',real).readOnly,true);assert.equal(loadState(JSON.stringify({schema:99}),real).readOnly,true);});
test('changed datasets warn and retain unmatched decisions',()=>{const old=loadState(null,real).state;old.dataVersion='old';old.rules.activities['removed-activity']=true;const next=loadState(JSON.stringify(old),real);assert.equal(next.state.rules.activities['removed-activity'],true);assert.equal(next.warnings.length,2)});
test('every PDF timetable row is linked and source hashes exist',()=>{const pages=JSON.parse(fs.readFileSync(new URL('../data/coverage.json',import.meta.url),'utf8'));assert.equal(pages.length,51);assert.equal(pages.reduce((n,p)=>n+p.rowCount,0),412);assert.ok(pages.every(p=>p.rowCount===p.mappedRows));assert.match(real.meta.sourceHash,/^[a-f0-9]{64}$/);});
