const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const data=JSON.parse(fs.readFileSync(path.join(__dirname,'../dist/agenda.json'))),out=process.env.UX_OUTPUT_DIR||path.join(__dirname,'../test-results/ux');fs.mkdirSync(out,{recursive:true});
const base=process.env.UX_URL||'http://127.0.0.1:4173',key='congreso-2-route-v1';
const pick=(date,start)=>data.activities.find(a=>a.date===date&&a.start===start&&a.end&&!a.auxiliary);
const later=pick('2026-10-08','09:10'),current=pick('2026-10-08','08:30'),tomorrow=pick('2026-10-09','08:30');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.BROWSER_PATH?{executablePath:process.env.BROWSER_PATH}:{})}),report=[];
async function session(ids=[],time='2026-10-08T11:00:00Z',options={}){const c=await browser.newContext({viewport:{width:390,height:844},timezoneId:'Asia/Tokyo',...options});const p=await c.newPage();p.setDefaultTimeout(8000);const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.clock.install({time:new Date(time)});await p.addInitScript(({ids,version,key})=>{if(!localStorage.getItem(key))localStorage.setItem(key,JSON.stringify({schema:1,dataVersion:version,rules:{rooms:{},blocks:{},activities:Object.fromEntries(ids.map(id=>[id,true]))},signatures:{}}));},{ids,version:data.meta.version,key});await p.goto(base);await p.waitForSelector('body[data-ready]');return {c,p,errors};}
try{
let {c,p,errors}=await session();assert.match(await p.locator('.personal-agenda').innerText(),/No tienes actividades guardadas/);assert.ok(await p.locator('.dense-talk').count());await c.close();report.push('empty route and general options');
({c,p,errors}=await session([later.id]));assert.equal(await p.locator(`[data-personal="${later.id}"]`).count(),1);assert.match(await p.locator('.personal-heading').innerText(),/09:10/);assert.match(await p.locator('.dense-section h2').first().innerText(),/08:30/);await p.screenshot({path:path.join(out,'Ahora-mobile.png')});
await p.locator('#navigation [data-tab=program]').click();assert.equal(await p.locator('[data-layout=time]').getAttribute('aria-pressed'),'true');await p.locator('[data-layout=room]').click();await p.locator('[data-room]').first().click();await p.locator('#searchButton').click();await p.locator('#search').fill('BI-RADS');assert.ok(await p.locator('.dense-talk').count()>0);assert.match(await p.locator('.search-status').innerText(),/Todas las salas/);await p.locator('#search').fill('ZZZ-nada-000');assert.match(await p.locator('#content').innerText(),/Sin resultados en este ámbito/);await p.locator('[data-action=clear-filters]').first().click();await p.locator('#searchScope').selectOption('all');await p.locator('#search').fill('BI-RADS');assert.match(await p.locator('.search-status').innerText(),/Todo el congreso/);await p.locator('[data-action=clear-filters]').first().click();await p.locator('#searchButton').click();await p.locator('[data-layout=time]').click();await p.evaluate(()=>scrollTo(0,0));await p.screenshot({path:path.join(out,'Programa-mobile.png')});
await p.evaluate(()=>scrollTo(0,650));const scroll=await p.evaluate(()=>scrollY);await p.locator('#navigation [data-tab=route]').click();assert.ok(await p.locator('.route-gap').count());for(const gap of await p.locator('.route-gap').all())assert.ok((await gap.boundingBox()).height<110);assert.ok(await p.locator('.compact-route').evaluate(e=>e.getBoundingClientRect().height)<650);await p.screenshot({path:path.join(out,'Mi-Ruta-mobile.png')});await p.locator('#navigation [data-tab=program]').click();assert.equal(await p.locator('[data-layout=time]').getAttribute('aria-pressed'),'true');assert.ok(Math.abs(await p.evaluate(()=>scrollY)-scroll)<5);
const title=p.locator('.dense-text').first();await title.scrollIntoViewIfNeeded();await title.focus();const titleID=await title.getAttribute('data-detail');await p.keyboard.press('Enter');assert.equal(await p.locator('#detail').getAttribute('aria-labelledby'),'dialogTitle');await p.goBack();await p.waitForFunction(()=>!document.querySelector('#detail').open);assert.equal(await p.evaluate(()=>document.activeElement.getAttribute('data-detail')),titleID);await p.locator('#navigation [data-tab=route]').click();await p.goBack();await p.waitForFunction(()=>document.body.dataset.view==='program');report.push('search all rooms/scope/empty/clear, compact gaps, retained layout/scroll, Back and focus');
await p.locator('#navigation [data-tab=now]').click();const real=await p.locator('#headerClock').innerText();await p.locator('[data-now-mode=custom]').first().click();await p.locator('#blockDate').selectOption('2026-10-09');await p.locator('#blockTime').selectOption('08:30');await p.locator('[data-action=apply-block]').click();assert.equal(await p.locator('#headerClock').innerText(),real);assert.match(await p.locator('#consultBanner').innerText(),/Consultando/);await p.locator('#navigation [data-tab=route]').click();assert.equal(await p.locator('#consultBanner').isVisible(),true);await p.locator('#consultBanner [data-now-mode=now]').click();assert.equal(await p.locator('#consultBanner').isVisible(),false);
await p.locator('#navigation [data-tab=program]').click();await p.setViewportSize({width:1440,height:1000});await p.locator('[data-layout=grid]').click();assert.ok(await p.locator('.schedule').count());await p.setViewportSize({width:390,height:844});await p.waitForFunction(()=>!document.querySelector('.schedule'));assert.equal(await p.locator('[data-layout=time]').getAttribute('aria-pressed'),'true');
for(const tab of ['now','program','route']){await p.locator(`#navigation [data-tab=${tab}]`).click();for(const width of [320,390,1440]){await p.setViewportSize({width,height:900});for(const zoom of ['100%','200%']){await p.evaluate(z=>document.documentElement.style.fontSize=z,zoom);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`${tab}/${width}/${zoom}`);const clipped=await p.locator('.dense-title,.dense-meta,.personal-speaker,.route-entry .activity-title').evaluateAll(es=>es.some(e=>e.scrollHeight>e.clientHeight+2));assert.equal(clipped,false,`clipped:${tab}/${width}/${zoom}`);}}}await p.evaluate(()=>document.documentElement.style.fontSize='100%');await p.setViewportSize({width:390,height:844});report.push('real vs consulted time, responsive table fallback, 320/390/1440 at 100/200%');
await p.evaluate(()=>navigator.serviceWorker.ready);await p.waitForFunction(()=>navigator.serviceWorker.controller);const stored=await p.evaluate(key=>localStorage.getItem(key),key);await p.reload();await p.waitForSelector('body[data-ready]');assert.equal(await p.evaluate(key=>localStorage.getItem(key),key),stored);await c.setOffline(true);await p.reload();await p.waitForSelector('body[data-ready]');assert.equal(await p.locator('#routeCount').innerText(),'1');assert.equal(errors.length,0,errors.join('\n'));await c.close();report.push('reload and offline preserve existing route');
({c,p,errors}=await session([current.id,later.id,tomorrow.id],'2026-10-08T11:35:00Z'));assert.ok(await p.locator(`[data-personal="${current.id}"]`).count());assert.ok(await p.locator(`[data-personal="${later.id}"]`).count());await p.clock.setSystemTime(new Date('2026-10-09T01:00:00Z'));await p.locator('[data-now-mode=now]').first().click();assert.ok(await p.locator(`[data-personal="${tomorrow.id}"]`).count());await p.clock.setSystemTime(new Date('2026-10-11T15:00:00Z'));await p.locator('[data-now-mode=now]').first().click();assert.match(await p.locator('.personal-agenda').innerText(),/No quedan actividades/);await c.close();report.push('current plus next, cross-day, after event');
const simultaneous=data.activities.filter(a=>a.date==='2026-10-08'&&a.start==='09:30'&&a.end).slice(0,2);({c,p,errors}=await session(simultaneous.map(a=>a.id)));assert.equal(await p.locator('[data-personal]').count(),2);await p.locator('.personal-agenda [data-action=conflicts]').first().click();await p.locator('[data-keep]').first().click();assert.equal(await p.locator('#routeCount').innerText(),'1');await p.locator('#closeDetail').click();await p.waitForFunction(()=>!document.querySelector('#detail').open);await p.locator('#toast [data-action=undo]').click();assert.equal(await p.locator('#routeCount').innerText(),'2');await c.close();report.push('simultaneous choices resolve and undo');
const failure=await browser.newContext({serviceWorkers:'block'});p=await failure.newPage();let failing=true;await p.route('**/agenda.json',r=>failing?r.fulfill({status:503,body:'unavailable'}):r.continue());await p.goto(base);await p.locator('#retry').waitFor();failing=false;await p.locator('#retry').click();await p.waitForSelector('body[data-ready]');await failure.close();report.push('load failure recovery');
console.log(JSON.stringify({passed:true,report},null,2));fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({passed:true,report},null,2));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});

