import fs from 'node:fs';
const data=JSON.parse(fs.readFileSync('dist/agenda.json','utf8'));
const rows=JSON.parse(fs.readFileSync('data/pdf-row-audit.json','utf8'));
const get=id=>data.activities.find(a=>a.id===id),changes=[];
function change(id,patch,reason){const a=get(id);changes.push({id,before:Object.fromEntries(Object.keys(patch).map(k=>[k,a[k]])),after:patch,reason,page:a.source.page});Object.assign(a,patch);}
change('e59',{title:'BI-RADS 3 en pacientes con cáncer de mama.'},'Página 30: el 3 es parte del título y no solo un distintivo de nivel.');
change('aux-110',{title:'Coffee Break'},'Página 21: el encabezado del bloque siguiente no forma parte de la pausa.');
change('e297',{title:'Bloque Hands-On II'},'Página 41: Empresas Auspiciadoras es un encabezado separado.');
change('e391',{speaker:'TM María José Prokes'},'Página 50: retirar el texto de clausura ajeno al nombre de la participante.');
change('e256',{title:'Encuentro Residentes',speaker:null,start:null,end:null,note:'El cuadro general (p. 4) lo sitúa el viernes por la tarde, en Salón 1 · Escultura. No informa horas de inicio/fin ni desglose; se retiró el intervalo 14:30–18:30 supuesto en el HTML original.'},'El PDF solo señala viernes PM; no hay respaldo para horas exactas.');
for(const id of ['e334','e369'])change(id,{title:'Presentación de trabajos científicos.',speakerRole:'moderator'},'Página 48: Modera indica el rol de Juan Pablo Cruz, no forma parte del título.');
change('e169',{roomId:'r-e652940808',blockId:'m-jueves-8-sal-n-7-polo-veterinarios-innovaci-n'},'Página 29: premiación de pósters de Veterinarios, en Salón 7 · Polo; no es clausura general en Vitacura.');
change('e8',{note:'Discrepancia en el PDF: la versión española (p. 16) indica esta charla y Dr. Felipe Reyes; la versión inglesa (p. 15), a la misma hora, indica «Cancer trials in Chile» y Dr. Christian Caglevic. Se conserva la versión española usada en tu HTML. Confirmar con la organización.',sourceVariants:[{page:15,title:'Cancer trials in Chile.',speaker:'Dr. Christian Caglevic'}]},'Las versiones inglesa y española discrepan; se conserva explícitamente la discrepancia.');
for(const a of data.activities){if(a.roomId==='r-6f04657a72'){a.roomId='r-ea0a6c3b50';a.source.roomPage=6;}if(a.roomId==='r-74022932b4'){a.roomId='r-e652940808';a.source.roomPage=6;}}
for(const b of data.blocks){if(b.roomId==='r-6f04657a72')b.roomId='r-ea0a6c3b50';if(b.roomId==='r-74022932b4')b.roomId='r-e652940808';}
changes.push({reason:'Plano de planta alta (p. 6): ICIS ocupa Salón 8 · Parque y SLARP precongreso ocupa Salón 7 · Polo. Se unificaron las salas conservando los IDs de actividades.'});
const aliases={e73:'e74',e75:'e74',e381:'e382',e383:'e382'};
get('e74').source.additionalPages=[20,24,26,28,30];get('e382').source.additionalPages=[44,46,47,48,49];
for(const [old,target]of Object.entries(aliases)){changes.push({id:old,mergedInto:target,reason:'Misma ceremonia y horario; las repeticiones en páginas de otras salas son referencias al evento común.'});}
data.activities=data.activities.filter(a=>!aliases[a.id]);
function splitBlock(page,cut,newId,newTitle,firstTitle){const items=data.activities.filter(a=>a.source.page===page),old=data.blocks.find(b=>b.id===items[0].blockId);old.title=firstTitle;const next={...old,id:newId,title:newTitle};data.blocks.push(next);for(const a of items)if(a.start>=cut)a.blockId=next.id;changes.push({page,reason:`Se separaron los bloques publicados: ${firstTitle} / ${newTitle}.`});}
splitBlock(19,'17:00','pre-slarp-casos-ii','Precongreso SLARP · Presentación de Casos Clínicos II','Precongreso SLARP · Presentación de Casos Clínicos I');
splitBlock(50,'15:50','tm-radiologia-intraoperatoria','Curso TM · Radiología diagnóstica e intraoperatoria','Curso TM · Imagenología Mamaria. Actualización, certeza diagnóstica y contraste.');
for(const b of data.blocks){const acts=data.activities.filter(a=>a.blockId===b.id);b.start=acts.map(a=>a.start).filter(Boolean).sort()[0]??null;b.end=acts.map(a=>a.end).filter(Boolean).sort().at(-1)??null;}
data.blocks=data.blocks.filter(b=>data.activities.some(a=>a.blockId===b.id));data.rooms=data.rooms.filter(r=>data.activities.some(a=>a.roomId===r.id));data.rooms.sort((a,b)=>a.name.localeCompare(b.name,'es',{numeric:true}));
const coverage=[];
for(const p of rows){const entries=[];for(const row of p.rows){let ids=row.ids.map(id=>aliases[id]??id).filter(id=>get(id));if(p.page===15)ids=data.activities.filter(a=>a.source.page===16&&a.start===row.start&&a.end===row.end).map(a=>a.id);if(!ids.length&&/INAUGURAL/i.test(row.text))ids=['e74'];if(!ids.length&&/CLAUSURA/i.test(row.text))ids=['e382'];entries.push({...row,ids});for(const id of ids){const a=get(id);a.source.references??=[];a.source.references.push({page:p.page,bbox:row.bbox,text:row.text});}}
 coverage.push({page:p.page,rowCount:entries.length,mappedRows:entries.filter(r=>r.ids.length).length,rows:entries,kind:p.rows.length?'agenda':p.page===4?'cuadro general':p.page===13?'leyenda niveles':[5,6].includes(p.page)?'plano':'información sin agenda horaria'});
}
for(const a of data.activities)a.verification='reviewed';
data.meta.version='2026-10-07-audit-1';data.meta.aliases=aliases;data.meta.auditStatus='reviewed';data.meta.auditSummary='391 registros de la base conciliados en 387 actividades únicas. 412 filas horarias del PDF vinculadas, incluidas la traducción inglesa y referencias repetidas a ceremonias. Una actividad sin horas publicadas y una discrepancia entre versiones idiomáticas están señaladas.';
const unmapped=coverage.flatMap(p=>p.rows.filter(r=>!r.ids.length));if(unmapped.length)throw Error('Quedan filas del PDF sin vincular: '+unmapped.length);
fs.writeFileSync('dist/agenda.json',JSON.stringify(data,null,2));fs.writeFileSync('data/corrections.json',JSON.stringify(changes,null,2));fs.writeFileSync('data/coverage.json',JSON.stringify(coverage,null,2));fs.copyFileSync('data/source/programa-2026.pdf','dist/programa-2026.pdf');
const overview=coverage.map(p=>`| ${p.page} | ${p.kind} | ${p.rowCount} | ${p.mappedRows} |`).join('\n');
const report=`# Auditoría del programa CChR 2026\n\nFuente: PDF comprimido aportado por el usuario (51 páginas), SHA-256 ${data.meta.sourceHash}. Base: CChR_2026_ruta_robusta.html, SHA-256 ${data.meta.baseHash}. Revisión: 7 de octubre de 2026.\n\n## Resultado\n\n${data.meta.auditSummary}\n\nSe conservó el contenido de la base; se contrastaron títulos, participantes, horarios y niveles contra texto posicionado del PDF. Se revisaron visualmente leyenda, planos y discrepancias. Las anomalías de niveles detectadas en páginas 24 y 36 eran desplazamientos gráficos de los distintivos; los niveles del HTML se conservaron tras revisión visual. Los títulos con números de nivel intercalados en la extracción no se modificaron por esa causa.\n\n## Incertidumbres de la fuente\n\n- Encuentro Residentes: viernes PM, Salón 1; sin horario exacto ni desglose (p. 4). No se calculan conflictos para esta actividad.\n- ICIS 12:00–12:20: versiones inglesa y española discrepan en título y participante (pp. 15–16). La app mantiene la española de la base y muestra ambas referencias. Confirmar con organización.\n- Este documento no verifica cambios publicados después de la edición del PDF aportado.\n\n## Correcciones documentadas\n\n${changes.map(c=>'- '+(c.id?c.id+': ':'')+c.reason).join('\n')}\n\n## Cobertura por página física\n\n| Página | Contenido | Filas horarias | Filas vinculadas |\n|---|---|---:|---:|\n${overview}\n\nLa página 15 repite en inglés la agenda ICIS; no se duplica en la app. Las ceremonias referidas desde varias salas se vinculan al evento de Vitacura. Los cuadros de resumen y planos no se cuentan como conferencias adicionales. Los 66 bloques originales se ajustaron a 67 bloques tras dividir dos agrupaciones y eliminar un grupo de clausura erróneo.\n\nArchivos auditables: data/coverage.json (cada fila y región PDF), data/corrections.json (antes/después), dist/agenda.json (datos de la app), data/source/ (originales).\n`;
fs.writeFileSync('docs/data-audit.md',report);
const esc=s=>String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
fs.writeFileSync('dist/audit.html',`<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Auditoría · Congreso 2.0</title><link rel="stylesheet" href="./styles.css"><main><a href="./">Volver a la agenda</a><h1 style="margin:20px 0">Datos y trazabilidad</h1><p class="notice">${esc(data.meta.auditSummary)}</p><p class="details-note">La versión española e inglesa del simposio ICIS difieren a las 12:00. El Encuentro Residentes solo informa viernes por la tarde. Ambas limitaciones aparecen en los detalles de sus actividades.</p><h2>Correcciones de la base</h2><ul style="line-height:1.8">${changes.map(c=>`<li>${esc(c.reason)}</li>`).join('')}</ul><h2>Cobertura del PDF</h2><p class="details-note">${coverage.reduce((n,p)=>n+p.rowCount,0)} filas horarias vinculadas a la agenda. Las repeticiones de ceremonias y traducciones enlazan a una sola actividad.</p><div style="overflow:auto"><table style="width:100%;text-align:left;border-spacing:0 10px"><tr><th>Página</th><th>Contenido</th><th>Filas vinculadas</th></tr>${coverage.map(p=>`<tr><td><a href="./programa-2026.pdf#page=${p.page}">${p.page}</a></td><td>${p.kind}</td><td>${p.mappedRows}/${p.rowCount}</td></tr>`).join('')}</table></div><p class="details-note" style="overflow-wrap:anywhere">PDF aportado por el usuario · SHA-256 ${data.meta.sourceHash}</p></main></html>`);
console.log(JSON.stringify({activities:data.activities.length,blocks:data.blocks.length,rooms:data.rooms.length,rows:coverage.reduce((n,p)=>n+p.rowCount,0),unmapped:unmapped.length,corrections:changes.length}));
